//! Data structures for QAMS reports.
//!
//! A [`Report`] is a dated collection of [`Review`]s (one filled-in
//! scorecard per agent per QA session). Reports answer three questions,
//! corresponding to the three report views described in `reports.md`:
//!
//! - **Overall summary**: for each criterion, what was the team's average
//!   percentage score across all reviews in this report?
//!   See [`Report::team_criterion_average`].
//! - **Agent-review index**: for each agent, what was their average
//!   percentage score across their reviews in this report?
//!   See [`Report::agent_average_score`].
//! - **Individual agent pages**: for a given agent and criterion, what
//!   option did QA select in each of their reviews (in chronological
//!   order), and what comment (if any) did they leave?
//!   See [`Report::agent_criterion_selections`].
//!
//! This module only models the data; CSV/JSON parsing and HTML rendering
//! for reports live in the CLI, mirroring how scorecard CSV/HTML parsing
//! and rendering were moved out of `qams_core::scorecard`.

use std::collections::HashMap;
use crate::scorecard::{Criterion, Scorecard};

/// A single completed review: one agent, one scorecard, one QA session.
///
/// Mirrors the JSON shape written by `scorecard.html`'s save action:
/// `{ agent, reviewer, date, selections, comments, score, adj_score?, metadata? }`.
pub struct Review {
    agent: String,
    reviewer: String,
    /// Review date, stored as the raw `YYYY-MM-DD` string from the form's
    /// `<input type="date">`. Kept as a string rather than parsed into a
    /// date type to avoid pulling in a date/time dependency; comparisons
    /// and range filtering can use ordinary string ordering since the
    /// format is fixed-width and zero-padded.
    date: String,
    /// Criterion name → selected option name.
    selections: HashMap<String, String>,
    /// Criterion name → optional QA comment on that criterion.
    comments: HashMap<String, String>,
    /// The score calculated by the review form at save time.
    score: f64,
    /// An optional score manually overridden by the reviewer.
    adj_score: Option<f64>,
    /// Review metadata field name → value (see `-r`/`--path-to-metadata`).
    metadata: HashMap<String, String>,
}

impl Review {
    pub fn new(
        agent: String,
        reviewer: String,
        date: String,
        selections: HashMap<String, String>,
        comments: HashMap<String, String>,
        score: f64,
        adj_score: Option<f64>,
        metadata: HashMap<String, String>,
    ) -> Self {
        Review { agent, reviewer, date, selections, comments, score, adj_score, metadata }
    }

    pub fn agent(&self) -> &str { &self.agent }
    pub fn reviewer(&self) -> &str { &self.reviewer }
    pub fn date(&self) -> &str { &self.date }
    pub fn score(&self) -> f64 { self.score }
    pub fn adj_score(&self) -> Option<f64> { self.adj_score }

    /// The score that should be used in aggregate calculations: the
    /// reviewer's manual adjustment if present, otherwise the calculated score.
    pub fn effective_score(&self) -> f64 {
        self.adj_score.unwrap_or(self.score)
    }

    /// The option selected for a given criterion, if this review covers it.
    pub fn selection(&self, criterion_name: &str) -> Option<&str> {
        self.selections.get(criterion_name).map(|s| s.as_str())
    }

    /// The QA comment left on a given criterion, if any.
    pub fn comment(&self, criterion_name: &str) -> Option<&str> {
        self.comments.get(criterion_name).map(|s| s.as_str())
    }

    /// Iterates over all (criterion name, selected option) pairs.
    pub fn selections(&self) -> impl Iterator<Item = (&String, &String)> {
        self.selections.iter()
    }

    /// The value of a given metadata field, if this review has one.
    pub fn metadata(&self, field_name: &str) -> Option<&str> {
        self.metadata.get(field_name).map(|s| s.as_str())
    }
}

/// A QAMS report: a named, dated bucket of reviews, generated by the
/// `report` command from all reviews dated within a start/end range.
pub struct Report {
    /// Human-readable label for this report, e.g. derived from its date
    /// range. Used as a row/column header when comparing reports.
    label: String,
    start_date: String,
    end_date: String,
    reviews: Vec<Review>,
}

impl Report {
    pub fn new(label: String, start_date: String, end_date: String, reviews: Vec<Review>) -> Self {
        Report { label, start_date, end_date, reviews }
    }

    pub fn label(&self) -> &str { &self.label }
    pub fn start_date(&self) -> &str { &self.start_date }
    pub fn end_date(&self) -> &str { &self.end_date }
    pub fn reviews(&self) -> &[Review] { &self.reviews }

    /// Reviews belonging to a given agent, in chronological order (by date
    /// string, which sorts correctly since dates are `YYYY-MM-DD`).
    pub fn agent_reviews(&self, agent: &str) -> Vec<&Review> {
        let mut reviews: Vec<&Review> = self.reviews.iter()
            .filter(|r| r.agent() == agent)
            .collect();
        reviews.sort_by(|a, b| a.date().cmp(b.date()));
        reviews
    }

    /// The distinct set of agent identifiers with at least one review in
    /// this report, in first-seen order.
    pub fn agents(&self) -> Vec<&str> {
        let mut seen = Vec::new();
        for review in &self.reviews {
            if !seen.contains(&review.agent()) {
                seen.push(review.agent());
            }
        }
        seen
    }

    /// **Overall summary view.** The team's average percentage score on a
    /// given criterion across every review in this report that covers it,
    /// using [`Criterion::get_avg_score`] over all selections made for that
    /// criterion. Reviews that don't include this criterion (e.g. due to a
    /// scorecard change) are simply omitted from the average.
    pub fn team_criterion_average(&self, scorecard: &Scorecard, criterion_name: &str) -> Option<f64> {
        let criterion: &Criterion = scorecard.criterion(criterion_name)?;
        let selections: Vec<&str> = self.reviews.iter()
            .filter_map(|r| r.selection(criterion_name))
            .collect();
        if selections.is_empty() {
            return None;
        }
        Some(criterion.get_avg_score(&selections))
    }

    /// **Agent-review index view.** An agent's average effective score
    /// (adjusted score where set, else calculated score) across all of
    /// their reviews in this report. `None` if the agent has no reviews
    /// in this report.
    pub fn agent_average_score(&self, agent: &str) -> Option<f64> {
        let reviews = self.agent_reviews(agent);
        if reviews.is_empty() {
            return None;
        }
        let total: f64 = reviews.iter().map(|r| r.effective_score()).sum();
        Some(total / reviews.len() as f64)
    }

    /// **Individual agent page view.** For a given agent and criterion,
    /// returns the selected option (and optional comment) from each of
    /// their reviews that covers that criterion, in chronological order —
    /// i.e. what gets shown side-by-side when an agent has multiple
    /// reviews within the same report.
    pub fn agent_criterion_selections<'a>(
        &'a self,
        agent: &str,
        criterion_name: &str,
    ) -> Vec<AgentCriterionEntry<'a>> {
        self.agent_reviews(agent)
            .into_iter()
            .filter_map(|review| {
                review.selection(criterion_name).map(|option| AgentCriterionEntry {
                    review,
                    option,
                    comment: review.comment(criterion_name),
                })
            })
            .collect()
    }
}

/// One cell in an individual agent page: the option QA selected for a
/// criterion in one of the agent's reviews, the review it came from (for
/// date/reviewer context), and the optional comment revealed on click.
pub struct AgentCriterionEntry<'a> {
    pub review: &'a Review,
    pub option: &'a str,
    pub comment: Option<&'a str>,
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use crate::scorecard::{Criterion, CriterionScore};
    use super::*;

    fn make_scorecard() -> Scorecard {
        let mut criteria = HashMap::new();
        criteria.insert(
            "greeting".to_string(),
            Criterion::new(HashMap::from([
                ("YES".to_string(), CriterionScore::Points(1)),
                ("NO".to_string(), CriterionScore::Points(0)),
            ])),
        );
        criteria.insert(
            "compliance".to_string(),
            Criterion::new(HashMap::from([
                ("YES".to_string(), CriterionScore::Points(1)),
                ("NO".to_string(), CriterionScore::Autofail),
            ])),
        );
        Scorecard::new(
            criteria,
            vec!["YES".to_string(), "NO".to_string()],
            vec!["greeting".to_string(), "compliance".to_string()],
        )
    }

    fn make_review(
        agent: &str,
        date: &str,
        greeting: &str,
        compliance: &str,
        score: f64,
        adj_score: Option<f64>,
    ) -> Review {
        Review::new(
            agent.to_string(),
            "QA Officer".to_string(),
            date.to_string(),
            HashMap::from([
                ("greeting".to_string(), greeting.to_string()),
                ("compliance".to_string(), compliance.to_string()),
            ]),
            HashMap::new(),
            score,
            adj_score,
            HashMap::new(),
        )
    }

    #[test]
    fn agent_reviews_filters_and_sorts() {
        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![
                make_review("Alice", "2026-06-05", "YES", "YES", 1.0, None),
                make_review("Ben",   "2026-06-03", "YES", "YES", 1.0, None),
                make_review("Alice", "2026-06-02", "NO",  "YES", 0.0, None),
            ],
        );

        let alice = report.agent_reviews("Alice");
        assert_eq!(alice.len(), 2);
        assert_eq!(alice[0].date(), "2026-06-02"); // chronological order
        assert_eq!(alice[1].date(), "2026-06-05");

        assert_eq!(report.agent_reviews("Nonexistent").len(), 0);
    }

    #[test]
    fn agents_lists_distinct_in_first_seen_order() {
        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![
                make_review("Ben",   "2026-06-03", "YES", "YES", 1.0, None),
                make_review("Alice", "2026-06-05", "YES", "YES", 1.0, None),
                make_review("Ben",   "2026-06-06", "NO",  "YES", 0.0, None),
            ],
        );
        assert_eq!(report.agents(), vec!["Ben", "Alice"]);
    }

    #[test]
    fn team_criterion_average_uses_all_selections() {
        let scorecard = make_scorecard();
        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![
                make_review("Alice", "2026-06-02", "YES", "YES", 1.0, None),
                make_review("Ben",   "2026-06-03", "NO",  "YES", 0.0, None),
            ],
        );
        // greeting: YES (1/1) + NO (0/1) = 1/2 = 0.5
        assert_eq!(report.team_criterion_average(&scorecard, "greeting"), Some(0.5));
    }

    #[test]
    fn team_criterion_average_none_when_no_reviews_cover_it() {
        let scorecard = make_scorecard();
        let report = Report::new("Week 1".into(), "2026-06-01".into(), "2026-06-07".into(), vec![]);
        assert_eq!(report.team_criterion_average(&scorecard, "greeting"), None);
    }

    #[test]
    fn team_criterion_average_none_for_unknown_criterion() {
        let scorecard = make_scorecard();
        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![make_review("Alice", "2026-06-02", "YES", "YES", 1.0, None)],
        );
        assert_eq!(report.team_criterion_average(&scorecard, "nonexistent"), None);
    }

    #[test]
    fn agent_average_score_prefers_adj_score() {
        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![
                make_review("Alice", "2026-06-02", "YES", "YES", 0.5, Some(0.9)),
                make_review("Alice", "2026-06-04", "YES", "YES", 1.0, None),
            ],
        );
        // (0.9 + 1.0) / 2 = 0.95
        assert_eq!(report.agent_average_score("Alice"), Some(0.95));
    }

    #[test]
    fn agent_average_score_none_for_unknown_agent() {
        let report = Report::new("Week 1".into(), "2026-06-01".into(), "2026-06-07".into(), vec![]);
        assert_eq!(report.agent_average_score("Nobody"), None);
    }

    #[test]
    fn agent_criterion_selections_chronological_with_comments() {
        let later = Review::new(
            "Alice".into(), "QA Officer".into(), "2026-06-05".into(),
            HashMap::from([("greeting".into(), "NO".into())]),
            HashMap::from([("greeting".into(), "Forgot to say hello".into())]),
            0.0, None, HashMap::new(),
        );

        let report = Report::new(
            "Week 1".into(), "2026-06-01".into(), "2026-06-07".into(),
            vec![
                later,
                make_review("Alice", "2026-06-02", "YES", "YES", 1.0, None),
            ],
        );

        let entries = report.agent_criterion_selections("Alice", "greeting");
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].review.date(), "2026-06-02");
        assert_eq!(entries[0].option, "YES");
        assert_eq!(entries[0].comment, None);
        assert_eq!(entries[1].review.date(), "2026-06-05");
        assert_eq!(entries[1].option, "NO");
        assert_eq!(entries[1].comment, Some("Forgot to say hello"));
    }

    #[test]
    fn review_metadata_accessor() {
        let review = Review::new(
            "Alice".into(), "QA Officer".into(), "2026-06-02".into(),
            HashMap::new(), HashMap::new(), 1.0, None,
            HashMap::from([("Call ID".into(), "12345".into())]),
        );
        assert_eq!(review.metadata("Call ID"), Some("12345"));
        assert_eq!(review.metadata("Missing"), None);
    }
}